### ISSUE TITLE
vootlivestreamer.sh not working

### ISSUE THREAD

**Issue by shoaibkhan94** [biezom/hotstarsportslivestreamer#15]
Snapshot of error attached
![image](https://cloud.githubusercontent.com/assets/8079189/19727033/4c60bf1e-9bab-11e6-8634-84768fa078ff.png)

**Comment by biezom** [comment]
hi
missing probably php5-curl package so

<pre>sudo apt-get install php5-curl</pre>

**Comment by shoaibkhan94** [comment]
Great. It's working after installing. Thanks for the quick reply!
