### ISSUE TITLE
throwing error while downloading movies

### ISSUE THREAD

**Issue by vishalwiw** [biezom/hotstarsportslivestreamer#3]
paste the link:http://www.hotstar.com/movies/neerja/1000090704/watch

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 135

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 139

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 141

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 143

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 155
Available streams:
write quality (example write 720p):720p
play or download? (write p or d):d

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 135

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 139

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 141

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 143

Notice: Trying to get property of non-object in C:\hotstarsportslivestreamer-master\hotstarlivestreamer.php on line 155
Starting livestreamer...

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 861, in main
  File "livestreamer_cli\main.py", line 566, in setup_args
  File "argparse.py", line 1688, in parse_args
  File "argparse.py", line 1720, in parse_known_args
  File "argparse.py", line 1732, in _parse_known_args
  File "argparse.py", line 1970, in _read_args_from_files
IndexError: string index out of range
Done.
Press any key to continue . . .

**Comment by biezom** [comment]
hi

just http://www.hotstar.com/movies/neerja/1000090704 without /watch
